pool:
  name: 'jerick-z440'

variables:
  KEY_SALT: 0
  system.debug: true

steps:
- task: CacheBeta@0
  inputs:
    key: $(KEY_SALT) | $(Agent.OS) | ./**,!./.git/**
    path: folder
    cacheHitVar: cacheHit
    restoreKeys: |
      $(KEY_SALT) | $(Agent.OS)

- bash: |
    mkdir folder
    echo Hello from $(Build.BuildId) > folder/hello.txt
  condition: and(succeeded(), eq(variables['cacheHit'], 'false'))
  displayName: cache miss

- bash: |
    echo Hello from $(Build.BuildId) >> folder/hello.txt
  condition: and(succeeded(), eq(variables['cacheHit'], 'inexact'))
  displayName: cache inexact hit

- bash: cat folder/hello.txt
  displayName: 'display hello.txt'
